// Generated by npm run generate:photo-board. Do not rescale or edit XY geometry.
// Marker data: OpenCV 4.11.0 extendDictionary(20,4), Apache-2.0; see /NOTICE.
board_width = 315;
board_height = 310;
board_thickness = 6;
board_corner_radius = 8;
marker_size = 30;
marker_ids = [16,17,18,19];
marker_centers = [[26,26],[289,26],[289,284],[26,284]];
marker_bits = [[[0,1,1,0],[0,1,0,1],[1,0,0,1],[1,0,0,1]],[[0,0,1,1],[0,1,1,1],[0,1,1,1],[0,0,1,0]],[[1,1,1,0],[1,0,1,0],[0,0,1,0],[0,1,1,0]],[[1,1,0,1],[1,0,0,0],[1,1,1,1],[1,1,1,1]]];
tile_size = 40;
tile_thickness = 2.4;
board_tile_clearance = 0.15;
tile_key_chamfer = 3;
adhesion_radius = 8;
adhesion_inset = 4;
adhesion_thickness = 0.4;
