import { markerBits } from "./aruco-4x4";
import { H2D_PHOTO_BOARD as board } from "./photo-board";
import { templateMarkerCentersMm, templateMarkerCornersMm } from "./template";

/** Generated OpenSCAD constants keep the printable model and detector in sync. */
export function photoBoardCalibrationScad(): string {
  const centers = templateMarkerCentersMm("h2d-photo-board");
  const values: Record<string, number | readonly number[] | number[][] | number[][][]> = {
    board_width: board.width,
    board_height: board.height,
    board_thickness: board.thickness,
    board_corner_radius: board.cornerRadius,
    marker_size: board.markerSize,
    marker_ids: board.markerIds,
    marker_centers: centers.map(({ x, y }) => [x, y]),
    marker_bits: board.markerIds.map(markerBits),
    tile_size: board.tileSize,
    tile_thickness: board.tileThickness,
    board_tile_clearance: board.tileClearance,
    tile_key_chamfer: board.tileKeyChamfer,
    adhesion_radius: board.adhesionRadius,
    adhesion_inset: board.adhesionInset,
    adhesion_thickness: board.adhesionThickness,
  };
  return [
    "// Generated by npm run generate:photo-board. Do not rescale or edit XY geometry.",
    "// Marker data: OpenCV 4.11.0 extendDictionary(20,4), Apache-2.0; see /NOTICE.",
    ...Object.entries(values).map(([name, value]) => `${name} = ${JSON.stringify(value)};`),
    "",
  ].join("\n");
}

/** Portable specification for other photo-calibration consumers. */
export function photoBoardManifest(): object {
  return {
    name: "Pocketry H2D photo board",
    template: "h2d-photo-board",
    version: 1,
    units: "mm",
    dictionary: "POCKETRY_4X4_V2",
    generator: "OpenCV 4.11.0 extendDictionary(20,4)",
    coordinateSystem: "Origin at top-left of finished board; x right, y down",
    dimensions: { width: board.width, height: board.height, thickness: board.thickness },
    markerSize: board.markerSize,
    markerCenterSpacing: { x: board.width-2*board.markerInset, y: board.height-2*board.markerInset },
    markers: templateMarkerCornersMm("h2d-photo-board").map((marker, index) => ({
      ...marker,
      center: templateMarkerCentersMm("h2d-photo-board")[index],
      bits: markerBits(marker.id),
    })),
    warning: "Marker IDs identify nominal dimensions; they cannot reveal uniform printer shrinkage. Print at 100% and verify physical spacing.",
  };
}
